import { writeFile, readFile, mkdir } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

import { fetchStats } from "./api/github.js";
import { renderHero } from "./render/hero.js";
import { renderStats } from "./render/stats.js";
import { renderActivity } from "./render/activity.js";
import { renderNow } from "./render/now.js";
import { theme } from "./theme.js";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const ASSETS = resolve(ROOT, "assets");

interface Asset {
  readonly file: string;
  readonly content: string;
}

/** Reads required env vars, failing loudly if absent (no silent defaults). */
function requireEnv(key: string): string {
  const value = process.env[key];
  if (!value) throw new Error(`Missing required environment variable: ${key}`);
  return value;
}

/** Writes a file only if its content changed — keeps the git history clean. */
async function writeIfChanged(path: string, content: string): Promise<boolean> {
  let current: string | null = null;
  try {
    current = await readFile(path, "utf8");
  } catch {
    current = null; // file does not exist yet
  }
  if (current === content) return false;
  await mkdir(dirname(path), { recursive: true });
  await writeFile(path, content, "utf8");
  return true;
}

/** Replaces the region between <!-- X:START --> and <!-- X:END --> markers. */
function injectSection(readme: string, marker: string, body: string): string {
  const start = `<!-- ${marker}:START -->`;
  const end = `<!-- ${marker}:END -->`;
  const pattern = new RegExp(`${escapeRe(start)}[\\s\\S]*?${escapeRe(end)}`);
  if (!pattern.test(readme)) {
    throw new Error(`README is missing markers for section "${marker}"`);
  }
  return readme.replace(pattern, `${start}\n${body}\n${end}`);
}

function escapeRe(s: string): string {
  return s.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

async function main(): Promise<void> {
  const login = requireEnv("GH_LOGIN");
  const token = requireEnv("GH_TOKEN");

  console.log(`[build] fetching stats for ${login}...`);
  const stats = await fetchStats({ login, token });
  console.log(
    `[build] ${stats.totalRepos} repos, ${stats.topLanguages.length} languages, ` +
      `${stats.recentRepos.length} recent, ${stats.contributions.currentStreak}d streak`,
  );

  const assets: readonly Asset[] = [
    { file: "hero.svg", content: renderHero(stats, theme) },
    { file: "stats.svg", content: renderStats(stats, theme) },
    { file: "activity.svg", content: renderActivity(stats, theme) },
    { file: "now.svg", content: renderNow(stats, theme) },
  ];

  let changed = 0;
  for (const asset of assets) {
    const path = resolve(ASSETS, asset.file);
    if (await writeIfChanged(path, asset.content)) {
      console.log(`[build] wrote ${asset.file}`);
      changed++;
    }
  }

  // README only embeds the assets via stable relative paths, so it rarely
  // changes — but we keep the injection step for future text sections.
  const templatePath = resolve(ROOT, "README.template.md");
  const outPath = resolve(ROOT, "README.md");
  let readme = await readFile(templatePath, "utf8");
  readme = injectSection(
    readme,
    "GENERATED",
    `<!-- assets regenerated by GitHub Actions; do not edit by hand -->`,
  );
  if (await writeIfChanged(outPath, readme)) {
    console.log("[build] wrote README.md");
    changed++;
  }

  console.log(`[build] done — ${changed} file(s) changed`);
}

main().catch((err: unknown) => {
  const message = err instanceof Error ? err.message : String(err);
  console.error(`[build] FAILED: ${message}`);
  if (err instanceof Error && err.cause) {
    console.error(`[build] cause:`, err.cause);
  }
  process.exit(1);
});
